### ISSUE TITLE
第2章 アプリケーションのソースコードを取得します 

### ISSUE THREAD

**Issue by tamikof** [covelline/kotlin_book#11]
- zipファイルがnot found
- chapter2ブランチがない
準備中？

**Comment by tamikof** [comment]
第2章の初期状態は
da72ec89036ba9c99a91427531eb046a70a8d5c0
にcheckoutでOKっぽい

**Comment by numa08** [comment]
タグ作るの忘れたorz

**Comment by tamikof** [comment]
↑のコミットからブランチ切って2章の手順通りに最初から最後まで行けたよ
